### ISSUE TITLE
Rec - Testing Recommendation Logic

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#148]
Need solution to test variable criteria - e.g. complete / incomplete, display in some weeks but not others.

**Comment by juliariffgit** [comment]
Some notes from our discussion:
Comprehensive manual test may be out of scope. John did manage to do a simple time-based manual test.

We have some open questions about where the timestamp comes from - personal machine v. server timestamp, etc. Also start date.

Basic: let's satisfy ourselves that the time mechanism is working.

--

Upshot: We will roll this into Unit Testing. We will ensure this is added.
