### ISSUE TITLE
Docker Class, PD

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#21]
This story is to allocate time for Brec to do a 10 hour course on using docker. This professional development will help him complete work on the business analytics epic, and develop the skill across other members of the team.

**Comment by juliariffgit** [comment]
Knows enough to accomplish story tasks.

**Comment by juliariffgit** [comment]
We still need an estimate for this. Brec to talk to Beth about this, then add to the story and close. Amy will look into why Brec doesn't have permission to add an estimate.
