### ISSUE TITLE
Docker container for mattermost analytics code

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#22]
## Description
Work has been done to select a tool for getting analytic information from our riffedu mattermost
database (mysql), and possibly also from our riffdata database (mongodb). The tool selected
was [metabase](https://metabase.com/).
In addition queries have been created to produce useful reports using metabase.

This story is to create a new repository with all the configuration, documentation, and scripts
to let another developer run metabase and a database locally and produce the defined analytic
reports.

The new repository will be [business-analytics](https://github.com/rifflearning/business-analytics).

- It should probably contain `docker-compose.yml` configuration that defines a metabase service
  and  whichever database services are needed.
- A `Makefile` would be useful to allow using the same commands as Riff developers currently
  use to run a development environment for RiffEdu (using `edu-docker`) or RiffPlatform
  (using `riff-docker`), ie `make up` and `make down`.
- Documentation on how to start up the services, set up the database (ie get and restore a backup)
  produce and publish the reports should be written either in the README.md or in markdown
  formatted documents in a `docs` subdirectory (or both, perhaps a summary in the readme
  with a reference to more extensive documentation in the docs folder).
- Helper scripts, perhaps needed for doing initial config or restoring database backups for
  subsequent analysis, should be in a `bin` subdirectory.

The goal is to have another Riff developer clone this repository and be able to produce the
analytic reports by using the scripts and following the documentation found in the repository.

**Comment by brecriffs** [comment]
@mlippert I am not sure if I have privileges to create a new repository. Could you create an appropriately named empty repo?

**Comment by brecriffs** [comment]
Have deployed a working development version to repo 'business-analytics'. Remaining tasks are as follows:
1. Provide documentation on how to run software
2. Create a 'Makefile' to allow for a seamless experience for Riff developers
3. Thoroughly QA sql queries and confirm accuracy of graphs/output
4. Test software with multiple course backups (optional)

**Comment by brecriffs** [comment]
1. Documentation almost complete
2. Makefile complete
3. sql queries have been QA'd by myself
4. multiple course backups/databases has not been tested

**Comment by ebporter** [comment]
1 story point of work still to be done by Brec -- to finish documentation, attach the repo to the ZenHub board, do an official pull request into Master.
MIke or Jordan will then test and review the documentation.

**Comment by brecriffs** [comment]
@mlippert Branch 'develop' will need to be force pushed to 'master' I believe. I started from scratch on the develop branch, and I think they have completely different commit histories. Also, I'm not sure how to attach the branch to this card...or can you only attach PR's?

**Comment by brecriffs** [comment]
Have responded to some requests from @mlippert. Waiting for feedback.

**Comment by juliariffgit** [comment]
@jaedoucette, ready for your review!

**Comment by jaedoucette** [comment]
@juliariffgit @mlippert @brecriffs Is the intention here that I review the work describe in the story (which would have me successfully clone the new repo and reproduce the results from the documentation), or review Brec's code, or both?

If I'm to do code review, can Brec request my review on the relevant PR?

Before I can review the functionality, I think the develop branch needs to be force-pushed into master?

**Comment by mlippert** [comment]
@jaedoucette You should review the functionality and also the code being created to implement it. I requested your review on the PR.

You don't need the code to be in the master branch to do that, just checkout the branch being merged by the PR.

**Comment by adonahue** [comment]
I agree w. @jaedoucette's PR review/comment- we don't want to store PII unencrypted on local machines. Not sure what that means in practice, or how we audit for that in what we're currently doing. @jaedoucette - thoughts on what the right approach is? We can also take this conversation out of the comments here. :)

**Comment by adonahue** [comment]
@jaedoucette @brecriffs - I don't think this story has any non-technical pieces for me to review. If that's not the case, please list what they are. Otherwise, if the code / technical review is done to the satisfaction of the dev team, @brecriffs please move this story to Complete / Accepted. Thanks!
