### ISSUE TITLE
Make GT Riff Usable without Special Link?

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#233]
As a PM, I am not sure if we should allow access to the GT-version of Riff, without an identity pass-through via Qualtrics. Is this change required anyway to implement documents based on room names that are specified by the user?

Pros
* It maintain the current product standard, where Riff site usable to any employee (as the current site is https://grantthornton.riffplatform.com/room). 

Cons
* It will require some level of dev effort
* It could introduce "noisy" data that doesn't have an identity match in Qualtrics

@jaedoucette - thoughts about this?

**Comment by jaedoucette** [comment]
@adonahue I'm not sure I completely follow. We should do a quick chat about this sometime tomorrow (Thursday).
