### ISSUE TITLE
Previous NEXT Metrics 11/19

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#253]
As a project manager, I need to present some basic metrics to NEXT on Wed 11/20, and will need the data and images by 11/19 so that I can prepare the presentation. I would like to use the the same metrics we provided for the last course, so we can have something quickly, and then follow on with the newer metrics that include new work and analysis. 

** Acceptance Criteria **
- [ ] A fresh copy of the Riff EDU database.
- [ ] All the stats previously developed with the metabase framework.
- [ ] The video statics previously reported (if separate from the metabase stats).
- [ ] Spreadsheet data and images for the metrics listed above; in a Google drive shared with @juliariffgit and the rest of the team.

**Comment by juliariffgit** [comment]
We talked through this and all feel it's best to deliver nothing until we can deliver what we discussed in https://app.zenhub.com/workspaces/riff-projects-5cb6029b4103d93ceadf001b/issues/rifflearning/zenhub/242
