### ISSUE TITLE
Meeting Mediator, a11y, add data tables

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#27]
As a non sighted user, I want to easily access and navigate the data associated with the meeting mediator. I would like a table for the percentage of speaking time and the number of turns, so I can access that information with my screen reader. 

Mockups for this design are slide one in this deck: https://drive.google.com/open?id=1T9AE35-FoCZjUbr9tZq2UGO9LJibAdkM

**Comment by arizzitano** [comment]
https://github.com/rifflearning/riff-rtc/pull/106

**Comment by arizzitano** [comment]
https://github.com/rifflearning/mattermost-webapp/pull/87

**Comment by adonahue** [comment]
@mlippert - just confirming this is deployed to both EDU and Platform staging. Thx!

**Comment by adonahue** [comment]
Tested this w. Ari in platform and edu. Accepting these PRs as accepted, and breaking out two pieces of work into a new story. 

A revised version of the "turn count" for the center ball, since we don't have a clear value judgement about High and Low energy. 

An enhancement to the EDU code that makes the MM a focus-able table, which results in a better screen reading and navigation experience.

**Comment by mlippert** [comment]
@adonahue Yes, the _deployed_ tag on the platform PR means it is deployed to staging.riffplatform.com, and the _deployed_ tag on the edu PR means it is deployed to staging.riffedu.com
