### ISSUE TITLE
Meeting Mediator, a11y, node and video labels

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#29]
As a Riff user, I would like more information about what the MM is displaying, so that I have the most useful information. 

- I would like to see a text-based association from the node to the video tiles, so that I understand which person is which node, and I don't have to rely on color only. 
- I would like to be able to click on a node and see the full username of the person whose data that represents, as well as their percentage of speaking time, so that I can better understand the dynamics of the conversation. 
- I would like to click the center node and see and explanation of the number displayed there, so that I understand what it represents. 

Mockups: slides 4, 5, 6 here: https://drive.google.com/open?id=1T9AE35-FoCZjUbr9tZq2UGO9LJibAdkM

**Comment by arizzitano** [comment]
PR here: https://github.com/rifflearning/riff-rtc/pull/118

**Comment by arizzitano** [comment]
Screenshots are in the PR, but I'll add them here too in case anyone would like to take a look: ![image.png](https://images.zenhubusercontent.com/5361a856e26d73e9370005d7/e984a358-daa9-454c-b067-103e7f6360b3) ![image.png](https://images.zenhubusercontent.com/5361a856e26d73e9370005d7/257104e7-e01e-49cb-8419-da241f3732cb)

**Comment by adonahue** [comment]
Adjustments:

- Add more white space btwn the letter and the outside of the node.
- Adjust letter positioning so letter is always horizontal when the nodes reposition.
![image.png](https://images.zenhubusercontent.com/5cbf1c836caba0089f532d44/a87fcf2d-2a99-457f-a835-6276431f165a)
- Fix wrapping on the tool tips. 
![image.png](https://images.zenhubusercontent.com/5cbf1c836caba0089f532d44/819854dc-2e00-4d02-97fc-ad508d912bf4)

**Comment by adonahue** [comment]
@arizzitano - this story does also include the usernames on the tiles and the tool tip for the turn count on the center node. LMK if you want to break those out into separate cards, or wrap them up on this.

**Comment by adonahue** [comment]
@arizzitano - looks great, thank you! 

Two small change requests, before merge: 
1) Some letters (lowercase "j") are still hitting the boarder on the node. Please adjust the padding / font size so that there is padding all around. 
![image.png](https://images.zenhubusercontent.com/5cbf1c836caba0089f532d44/26cfeca3-988d-4de8-93e8-d5d20285eb6b)

2) The color bars look a little heavy - is it possible reduce the transparency, and still maintain a passing contrast ratio? If so, please make that change as well.

**Comment by arizzitano** [comment]
Done and done. I kept the opacity at 100% for the name label itself, so contrast shouldn't be an issue. Here are some screenshots: ![image.png](https://images.zenhubusercontent.com/5361a856e26d73e9370005d7/1e2aeaa8-fc44-4603-8222-c65c17db7a0e) ![image.png](https://images.zenhubusercontent.com/5361a856e26d73e9370005d7/c824cdfb-d2f2-4ad0-a98a-4105f2139c30)

**Comment by adonahue** [comment]
Moving this comment to #28, which addresses the info box specifically. The criteria for this story are met.

@arizzitano - When I test this w. Vox / Chrome / PC, The MM box does not take focus, front or back, and the info / close control does not get read out on focus. I now Vox is not a great A11y tool - did you test any of this w. your better tools?

@ebporter - would you mind looking at this quick in Safari / VoiceOver, to see if you get the same results as I listed above? 

Other Notes:
- [ ] Typo on back of card (and update "click" language).
