### ISSUE TITLE
SPIKE: Options to monitor and log stability metrics

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#30]
As a Riff user, it's important to me to have uninterrupted video and and audio with all the other participants in my meeting, so that I can have a cohesive, uninterrupted conversation.

As a product manager, I want objective stability data that I can correlate with specific users so that I have a way to quantify a "poor" video call because of technical limitations, and cross-reference that with user reports. I want to understand what should be communicated to users for technical requirements to increase the likelihood of a good UX. 

This spike is to allocate time to figure out what stability data we can discover and log, in order to better understand the requirements for a good quality Riff video meeting. 

**Background and Context** 
Users in the first NEXT course run reported technical issues with Riff, primarily:
- Calls dropping
- Call freezing video
- Calls freezing audio
- Poor audio quality
- Poor video quality 

@jordanreedie gave an initial assessment that these issues are likely caused by one or more of the following problems:
- Strength of connection, measured by how much bandwidth (up and down) a user has.
- Stability of connection, measured by how many packets are lost because of an unstable WiFi connection or other environmental interference
- Quality of audio, i.e. things like the quality or directionality of a mic, how much background noise there is, if a person is using headphones, etc. 

** Story Acceptance Criteria **
A written recommendation proposing how we can:
- measure and log strength of connection (possibly via the WebRTC estimate)
- measure and log stability of connection 
- is it possible to log when a call is attempted but not able to connect?
- cross reference connection stability and strength measurements with individual users sessions and specific meetings, so that we can see what kind of connections users had in their meetings.
- A recommendation for what if any of this work could be completed and deployed for the second course run, and if not, what other approaches might help us better understand and improve the quality of Riff video calls for that course run.

**Comment by jordanreedie** [comment]
Ok, so it looks like there are a few options, but only one of them really seems viable.

The easiest: We go with an off-the-shelf solution for monitoring performance in webrtc applications. There's really only one out there right now (callstats.io). Unfortunately, it costs about $2000 USD per month (list price is 1800 euro). That seems untenable.

This leaves us with two options: Roll our own monitoring service / library or use an open source one. Rolling our own would almost certainly take more time than we have to allocate to this.

There is currently one open source library for this - rtcstats (https://github.com/lifeonairteam/rtcstats). This looks like what we want, however the documentation is *very* sparse. It requires an additional server to be run (https://github.com/lifeonairteam/rtcstats-server), with hookups to amazon firehose, redshift, and s3. Figuring out how to set all this up will probably take a while, but it seems like the best option to me.

**Comment by adonahue** [comment]
Accepting story based on @jordanreedie summary. Further work is specified in story #128. https://app.zenhub.com/workspaces/riff-projects-5cb6029b4103d93ceadf001b/issues/rifflearning/zenhub/128
