### ISSUE TITLE
Post-Facto Code Review of Dashboard and Chat Refactor

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#31]
## Description
This story is to allocate time to review refactored dashboard code, that did not yet get reviewed. 

- Review code for structure and style conventions
- Read / review for learning of code and to inform continued refactoring work across the team, e.g. naming choices, global and local variables, type definitions, redundancy, etc. 
- Review for clarity and quality

### Dashboard PRs to be reviewed
- From story _Dashboard: Refactoring for style_ rifflearning/riff-rtc#72
    1. rifflearning/riff-rtc#70
    1. rifflearning/riff-rtc#82
    1. rifflearning/riff-rtc#100
    1. rifflearning/riff-rtc#101
- From story _Dashboard: Refactoring for style_ rifflearning/riff-rtc#83
    1. rifflearning/riff-rtc#103
    1. rifflearning/riff-rtc#104

### Chat PRs to be reviewed
- From story _Chat: Refactoring for style and modularity, First Half_ rifflearning/riff-rtc#78
    1. rifflearning/riff-rtc#105

**Comment by adonahue** [comment]
@mlippert - can you attach or reference the PRs for the code that needs to get reviewed?

**Comment by jordanreedie** [comment]
I've looked over Mike's (many) PRs and it all makes sense to me

**Comment by mlippert** [comment]
I've looked over Jordan's PR and it all looks good, so I've merged it and it is deployed.

**Comment by jaedoucette** [comment]
If this was the one Brec & I did together, I believe it was 5 hours of review.
