### ISSUE TITLE
Brightscout Code Review and Integration, deployment

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#32]
This is to allocate Mike's time to integrate the Brightscout survey work.

**Comment by mlippert** [comment]
I've deployed the 2nd survey plugin release from Brightscout, [version `v0.3.0`](https://github.com/Brightscout/mattermost-plugin-survey/releases/tag/v0.3.0) to staging.riffedu.com

**Comment by ebporter** [comment]
Creating another task for Sprint 3

**Comment by ebporter** [comment]
Closing this issue
