### ISSUE TITLE
Metabase Reports for Julia

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#33]
This story is to allocate time for generating metabase metrics on EDU usage and delivering them to Julia for the purposes of status reporting to NEXT. It includes the following tasks:

- [x] Run and deliver reports on the queries that have already been developed, so that we can see the format and style that gets generated (e.g. graphics, data tables, etc.) 
- [x] Review the remaining user stories to determine difficulty of work to write the queries, so that remaining queries can be prioritized.
- [x] Write those queries. 
- [x] Deliver final set of reports to Julia by **5/22/19**

Story document is here: https://docs.google.com/document/d/1YAcCUbBUooDOW4bmeeDkrE7Fjyd7s2Fajuitd0TRL5I/edit

**Comment by brecriffs** [comment]
Note to self:
Make sure times on graphs are in EST!

**Comment by brecriffs** [comment]
Now meeting with Julia at 2pm on Thursday to output reports

**Comment by brecriffs** [comment]
Completed 'How many text conversations spin off live video chats' query

Will review/research/implement 'Typical Riff Edu session/usage' today
