### ISSUE TITLE
Design Experiment 

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#38]

**Comment by jaedoucette** [comment]
A draft design is now up here: https://docs.google.com/document/d/1NjwE9ChCGNzXA1KqNq_jseWDS5fDvrOW9491DTgo8CI/edit?usp=sharing

and ready for review @adonahue

**Comment by adonahue** [comment]
Thank you @jaedoucette - I will take a look. @ebporter is the owner for final design approval.

**Comment by adonahue** [comment]
This story is currently blocked business decisions about the following: To resolve, @adonahue @ebporter and @jaedoucette need to discuss and decide before 6/26. 

- [ ] Concerns / implications / alternatives to the proposed Dev work in the current design. 
- [ ] Initial power analysis by @jaedoucette suggested a prohibitively large participant group. John will do some additional research to see if a variation can be used. Otherwise a different task might be required. 
- [ ] How much of the design should be for a reusable experiment framework, v. a one-off to fulfill the grant requirements. 
- [ ] Date driven, or other requirements to fulfill the terms of the grant.
- [ ] Date driven requirements related to other business objectives (e.g. additional grant funding deadlines.

**Comment by ebporter** [comment]
@jaedoucette @adonahue  I've read through the entire Experiment Design document and I'm ready to talk about this in our meeting on Monday morning. I'm generally in favor of what the typing task can help us prove, but I don't want to discount the group moral reasoning task as a viable option either, because it *seems* more closely related to the kind of work that people get together in meetings to accomplish.

**Comment by adonahue** [comment]
Have decided to move forward with the Moral Reasoning task for the following reasons:

- It more closely mimics the type of behavior (group discussion for the purpose of decision making) that we expect Riff to be used for.
- It is a reasonable measurement of C.
- It can be used to replicate previous studies of the MM, but in a purely virtual environment (no badges). 
- It is a better measure of turn-taking than the typing task.
- It will measure dominance.
- It will measure the direct effect of the MM.
- It may have a lower implementation cost. 
- More statistical power. 

What will NOT get
- A higher measurement of C.
- A solid measurement of sequential learning, since we do not have a second, validated activity to use (i.e. learned effect). 

@jaedoucette and @ebporter - please augment the above as needed, I feel a little light on the trade-offs section. 

NEXT STEPS
- Basic UX / workflow and functional requirements to begin scoping Dev effort. @adonahue 
- Experiment design detail. @jaedoucette 
- Second activity and scoring rubric @jaedoucette @ebporter 
- Review initial requirements w dev team for feedback.

**Comment by adonahue** [comment]
@jaedoucette - I'm not complete sure how to close out this story. I think that the original scope of this work is mostly fulfilled. Can we connect to chat?

**Comment by adonahue** [comment]
This story is complete, we are now moving into the phase of figuring out how to implement the experiment.
