### ISSUE TITLE
Power analysis for number of participants

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#41]

**Comment by jaedoucette** [comment]
@adonahue 

I think this is now ready to close, barring further changes to the experiment. Analysis is in the Power Analysis sub-section of this document: https://docs.google.com/document/d/1NjwE9ChCGNzXA1KqNq_jseWDS5fDvrOW9491DTgo8CI/edit?usp=sharing

**Comment by adonahue** [comment]
Thanks @jaedoucette - can you just add an estimate for the total time you spent on this task?

**Comment by jaedoucette** [comment]
I entered 1 for the Zenhub estimate. Including the initial estimate, scoping of the hypotheses, determining the testing involved, and the re-doing of the analysis at the end it _might_ have been a full day of work. Maybe more like 4-6 hours total would be my best guess
