### ISSUE TITLE
Identify and report on all potential data sources for Riff research projects

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#44]
As a researcher, I want to understand all the data sources available to me, and their formats, so that I can figure out how to build an integrated data pipeline. 

This story is about creating a catalog of all our data resources that John might use for research, so he can hit the ground running when he comes on board. The goal is to be able to put enough information into this document so he has the gist of what's available to him, and how to access it (both where it is, and who the gatekeeper is). 

Story Acceptance Criteria

- A written document that contains the following information
- [ ] Data Description and business purpose 
- [ ] Data format
- [ ] Reference documents (e.g. schema, documentation, etc.)
- [ ] How is it accessed (e.g. where it's located and who knows about it. )

**Data Sources**

- [x] Qualtrics surveys for the NEXT Canada course
- [x] Course gradebook and performance data (open edX)
- [ ] Activity data for the course (user interaction and engagement)
- [x] Riff platform data - video and audio
- [x] Riff platform activity data (firebase)
- [x] Mattermost data
- [x] Brightscout Survey Data
- [ ] Other ones we forgot

**Comment by juliariffgit** [comment]
John won't have time to start until the second half of sprint 3.

**Comment by jaedoucette** [comment]
Reference document = location and/ or example

**Comment by jaedoucette** [comment]
Brec -> Mattermost
Jordan & Mike -> Riff Data
Beth -> Qualtrix?

**Comment by jaedoucette** [comment]
Deep dive for next sprint.

Talk to everyone on the team.

**Comment by jaedoucette** [comment]
@adonahue 

Before I proceed with making writeups for the other databases, I wanted to confirm that this this is roughly what we had in mind for this task:

https://docs.google.com/document/d/1oiFNiGTsvMTSpuuqotMLAA2VLotsjoEFL2kuncCL1Mw/edit?usp=sharing

**Comment by adonahue** [comment]
@jaedoucette - this looks great, thank you. I updated the story description a little bit for clarity, but you've basically covered all that in what you wrote.

**Comment by jaedoucette** [comment]
Draft reports have now been completed for most (all?) data sources.

Reports are stored in this folder: 

https://drive.google.com/open?id=1heJhIaPWU0fk8nOVcC8xPPSytRQ-mngq

**Comment by jaedoucette** [comment]
Ready for review/QA by @adonahue!

**Comment by adonahue** [comment]
@jaedoucette - I think I've read through everything now. Very helpful! There are a number of outstanding questions, but I think in terms of the work this story represent - getting the documentation and discussion established - this story is done. Marking as complete.
