### ISSUE TITLE
SPIKE: Dashboard and Metrics Design Update

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#53]
As a PM, I want an updated and cohesive looking dashboard, so that the product looks slick and professional when we pitch to clients and investors. I also want to be able to produce new metrics quickly and have them match the design aesthetic we choose. Anything that saves us implementation time by using existing design pattern libraries is preferable to coding everything from scratch. 

** Story Tasks **
- [ ] Research UI pattern libraries for React and make 2 - 3 recommendations based on: 

* open source,
* license - cost (free is ideal) and reusabilty in a commercial product, 
* look and feel to support a cohesive, attractive design aesthetic across all metrics and new metrics. 
* ease of integration, with current code
* extensibility, as we add in new metrics and need to customize design patterns
* support for a11y. 
* responsiveness for scaling (e.g. will display nicely on mobile)

**Story Acceptance Criteria:**

A written recommendation (including pros and cons) for options that we can use going forward. It should include sample images of the design to communicate the look and feel of what will get rendered.

**Comment by brecriffs** [comment]
# Discovery for amcharts

### Open source
* With OEM license
* Without access to the source code, we are somewhat limited by the out-of-the-box features, however, they are plentiful and I was able to get a quick answer from the community on github regarding an issue I was having

### Ease of integration
* Has react components that can be easily installed view its npm package

### Extensibility
* Lots of beautiful, highly functional graphs out of the box that can be easily customized and spun up quickly

### A11y
* The charts seem to have a lot of accessibility functionality out of the box
* I tested locally with ChromeVox and was able to use the tab button to move around the graph. The default aria-labels can be changed by the implementer
* More information about its accessibility features can be found here: https://www.amcharts.com/accessibility/accessible-charts/

### Responsiveness 
* All charts and maps are responsive out of the box, adjusting the features and widths based on the available screen space
* More information about its responsiveness can be found here:
https://www.amcharts.com/docs/v3/tutorials/making-charts-responsive/

**Comment by brecriffs** [comment]
![Screenshot from 2019-07-03 09-30-39.png](https://images.zenhubusercontent.com/5cc9e71e5c551f0edc55e96f/50b83384-a8e9-402a-a683-e9bb3186c4f3)

Here is a screenshot of some experimentation I've done so far. It will be hard to match the exact design for the Network Graph without having access to the source code. My idea was to have two main nodes. One for you and your team, and another node for the course. This is what ebporter would see in her dashboard. The size of each peer node is relative to the aggregate count of the interaction types, which I thought would be neat. There is an example of a tooltip showing. Lots of considerations to be made here, and it would be great to meet with Amy when she is back from OOO to discuss business requirements and UX.

What I've done so far on the front-end is dynamic, and can easily be extended upon for more interaction types.

**Comment by brecriffs** [comment]
![Screenshot from 2019-07-05 17-35-50.png](https://images.zenhubusercontent.com/5cc9e71e5c551f0edc55e96f/3c1268dc-1a9f-4552-85a7-60f0c011b3be)

An example inside edu. No tooltips, more variation in node size.

**Comment by brecriffs** [comment]
An example inside edu. No labels (just tooltips), more variation in node size.
![Screenshot from 2019-07-05 17-40-55.png](https://images.zenhubusercontent.com/5cc9e71e5c551f0edc55e96f/6e38781e-3562-4a98-9d69-4486077dc66e)

**Comment by adonahue** [comment]
@brecriffs - from my perspective, this spike is complete, given that we've made a decision to license amCharts. Anything else that you think this story requires, or can I close it?

**Comment by brecriffs** [comment]
@adonahue Agreed, I think it can be closed.
