### ISSUE TITLE
Data Pipeline Design, Consolidate Data

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#61]
This card is to allocate time for @jaedoucette to gather information about Riff data sources and begin to design how all the data need to come together into a system that supports Riff research.

** Steps for collecting data and loading into memory **

Consolidate Data
- [ ] Mike places regular backups of SQL & Mongo data in a "backups" folder on Google Drive.
- [ ] John places supplemental, static, csv data sources in a "Data" folder on Google Drive.
- [ ] A Python program pulls all sources into memory at once.

Notes:

- In future, all data should be automatically backed up to something like Amazon S3 on a regular basis, and ideally the merging of the data and the analytics work occurs then.
- This design is going to have a moderate amount of redundant data (specifically, data relating to teams is going to be replicated across many users). The main advantage of this format is that it is extremely easy to ingest for a wide variety of analytic tools. If storage overhead becomes an issue, this should be revisited, but this is probably not a problem until we have 10k+ active users, maybe considerably more.
- It would be useful to be able to do incremental updates, especially when the databases become large. This should probably occur in the scripts that extract the data, but it seems premature to build that infrastructure now.

**Comment by jaedoucette** [comment]
Moved comment to description.

**Comment by adonahue** [comment]
@jaedoucette - my sense from talking this morning was that this task is done (as written now). If that's the case, please move to the next pipeline on the board. If there are remaining tasks, please add them to the story so we can estimate tomorrow. 

The rest of what was in this original story is now in cards #66 and #67.

**Comment by jaedoucette** [comment]
@adonahue - I need about half a day more work to finalize this initial module, but anticipate moving it to the next pipeline by end of day.
