### ISSUE TITLE
Contact research on alternative power analysis options

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#68]
@jaedoucette 's initial power analysis indicated a very large number of users would be required to account for the variance in the results. It is possible that an adjustment to how things are measured will reduce that variance in a way that allows us to precede as designed. 

This card is to allocate time to contact researchers, and do the analysis on what might be possible given the current experiment design. Also, something about non-parametric tests? 

@jaedoucette - can you clarify the details as needed for the requirements for this story?

**Comment by jaedoucette** [comment]
Avenues to explore:

[x] Contact Prof. Woolley @ CMU and ask for distributional information about the Group Typing Task.
[x] Contact Gupta or Bates and ask them for distributional information about the Group Typing Task.
[] Find some volunteers (Other Riff'ers, friends or acquaintances) who can spare 10 minutes to try the task with a Google Doc + honor system. Measure typical performance and variance (but this is not a representative sample).
[] Try to uncover further research using this task that might report variance information (there doesn't seem to be a ton more I can check).

**Comment by jaedoucette** [comment]
This task was addressed by agreement with @ebporter and @adonahue to move to the Group Moral Reasoning task. The power analysis was completed for that task led to favorable results, so no further work on alternatives is required.

**Comment by adonahue** [comment]
Thanks @jaedoucette - closing.
