### ISSUE TITLE
Implement Styling Recommendations to Refactored Video and DB Code

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#69]
After completing the test case of Login and Profile pages, (#111) apply the agreed upon style to the rest of the refactored code.

**Comment by adonahue** [comment]
We have not reached a decision as a dev team for best approach a styling convention. This should be deferred until we have an approach to styling.

**Comment by adonahue** [comment]
@brecriffs - now that #111 has closed - is this still work that needs to be done? If so, @ebporter - is it something you can help me understand the priority of, and get written so @brecriffs can stay focused on the network graph node?

**Comment by brecriffs** [comment]
I think it makes sense to postpone this.

**Comment by juliariffgit** [comment]
@Amy, I don't think there's any additional work to do on this story at the moment. @mlippert  already took Brec's structure for the scss files in the project, and did the Dashboard refactor work.

In the future, we might consider asking Frances to weigh in with pros and cons and considerations for other possible approaches, but this is not planned work at the moment.

We could either move this to the icebox or close it out.
