### ISSUE TITLE
Network Graph, Render in EDU Dashboard

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#70]
Once we have coded the network graph visualization, and pull live data from Mm, we will need to render it in the EDU dashboard. This piece of work is just for initial rendering, and should take into account that there will be some additional dashboard design that creates a new presentation that allows for individual meeting metrics, as well as longitudinal metrics like the network graph. 

** Open Questions ** 

* Can the force directed tree graph show group nodes that *haven't* connected, i.e. show group members that you haven't reached out to?
* Can we count Riff video sessions, or are we limited to just Mm data?
* Is it important to weight certain kinds of contact, or is a total count sufficient for a first implementation?
* Where are we going to pull data updates from, and how frequently?

Mockups and design comments are here, wireframes "Network graph, 2" and "Network graph, 2 back":
https://drive.google.com/open?id=1uSoqdZEDtI0DR_urOweDE34U17tocSRW

**Comment by adonahue** [comment]
@brecriffs - you've done some or all of this work, and presumably tracked it on story #72? Does it make sense to just keep everything there, or does this card have any use for identifying the distinct piece of (rough) dashboard work. 

I've now added some questions to this story about how to finish the work, so keeping this card for the moment.

**Comment by juliariffgit** [comment]
will split research/weighting question into another card.

**Comment by adonahue** [comment]
Break out into different stories:

- Visual enhancements
- Getting and integrating Riff video data
