### ISSUE TITLE
Network Graph, EDU Dashboard Re-Design

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#71]
* As a user, I want to understand why Riff metrics matter in the context of my course, and how I should use them. 

Once we have completed the development work on the new network graph metric, we will have some re-design work for the dashboard to incorporate it in a way that makes sense, since currently, metrics are all oriented to individual meetings. 

I am working on designs, which include these elements in the dashboard:

* Basic (pre-defined)  recommendations, based on user contact activity.
* A page header on the dashboard to Title and explain what it is. 
* The network graph to always display at the top, since it updates over time.
* To list meeting participants. 
* Group name.
* To list the actual start time of the meeting. 
* To identify the last meeting, distinct from the rest of the meeting history. 
* To resize the other metrics for a more balanced / compact presentation. 

Mockup and design comments are here, wireframe "EDU dashboard":
https://drive.google.com/open?id=1uSoqdZEDtI0DR_urOweDE34U17tocSRW

**Comment by mlippert** [comment]
Might I also suggest that the scrolling list of metrics for past meetings is not a good way to go, and that I think it would be better to have some way to select the meeting you want to see metrics for.
