### ISSUE TITLE
Additional Dashboard Refactor Work

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#73]
This card is to document additional DB refactor work that was discovered and completed as a result of investigating bug #65. This code did not address the bug itself, but did result in additional refactoring of dashboard code.

**Comment by adonahue** [comment]
Here you go @mlippert - add any other relevant details as needed.

**Comment by adonahue** [comment]
@mlippert - is there anything specific for me to test or review? Thanks!

**Comment by mlippert** [comment]
If the dashboard still shows the meeting info then I guess this is working.

**Comment by adonahue** [comment]
Ok, closing out.
