### ISSUE TITLE
Code Review: Data Pipeline Design, Blend and Anonymize Data

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#77]
Code Review Time Tracking card for story #66. 

** Directions **
- When you begin review on a PR, add your name and estimate for the time you think the code review will take you.
- Track your total time as a running tally in the description (here) of the card.

**Comment by brecriffs** [comment]
Brec - estimating 2 hours

**Comment by mlippert** [comment]
2-3 hours spent reviewing.

Why is the PR for the functionality attached to the Code Review story? Isn't there a story for the implementation?

**Comment by jaedoucette** [comment]
4.5 hours spent addressing review comments on this for the 2 features.

@mlippert There is/was a code review story, but I wasn't sure whether to associate with the original card or the code review card (the zenhub plugin only allows 1?). Probably the code review card is the right choice in future.

**Comment by mlippert** [comment]
@jaedoucette I believe that PR's should be associated with the story that describes the work they are implementing.

THIS is a code review story, I think the PR should NOT be attached to this story, it should be attached to the original story.

 The description of a Code Review story should link to the PR that is supposed to be reviewed I guess. As I said I found it all a pain to deal with.

**Comment by jaedoucette** [comment]
@mlippert Got it. I misread the name (missed the "Code Review"). In future I will link the PR to the issues, and not to the code review stories. 

This makes me think we should just have one card, and leave estimated hours spent in code review attached to it. That creates a record, but fits better with out existing automation.
