### ISSUE TITLE
Code Review: dashboard refactor pt5 

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#81]
Code Review Time Tracking card for story #127. 

** Directions **
- When you begin review on a PR, add your name and estimate for the time you think the code review will take you.
- Track your total time as a running tally in the description (here) of the card.

**Comment by adonahue** [comment]
@mlippert @jordanreedie Can you guys please add your code review time to this card? Thanks!

**Comment by mlippert** [comment]
I think I spent 2-3 hours on this

**Comment by jordanreedie** [comment]
I spent around 45 minutes I think

**Comment by jaedoucette** [comment]
If this was Jordan's big PR, I have it as 3 hours.
