### ISSUE TITLE
Find a suitable queuing / meeting room provider.

### ISSUE THREAD

**Issue by jaedoucette** [rifflearning/zenhub-platform-project#94]
Find a queuing / meeting room provider.

Needed features:

 - Participants can join an announce-only channel moderated by our facilitators.
 - Participants cannot make their own channels
 - We can display (via bot) a welcome message when new users join.
 - We can make new channels for just some participants.
 - We can launch Riff easily.

This all sounds like RiffEDU. Todo:
[x] Ask Mike about the feasibility of using RiffEDU for this; setting up another instance, etc.

**Comment by adonahue** [comment]
@jaedoucette - I don't think Riff EDU has the ability to let user's join anonymously, but it's possible there's a setting in Mattermost that does allow that. If not, participants would have to register to get into chat, which might increase the drop rate.

**Comment by jaedoucette** [comment]
@adonahue Looks like you're right. There's an outstanding feature request [here](https://api.mattermost.com/#tag/users), and various plugins like [HybridChat ](https://hybrid.chat/) that claim to offer some kind of integration for this.

We could potentially automate the registration process (mattermost API has a [simple function for this](https://api.mattermost.com/#tag/users%2Fpaths%2F~1users%2Fpost)), but they'd still need to sign in with a valid email address, which is a problem.

@adonahue Can you remind me what the problem was with Dead Simple Chat?

**Comment by adonahue** [comment]
@jaedoucette I have some notes at the bottom of the MVE document. But in short, I think we will lose users attention while they're waiting and it will be hard to ping them to get it back. I'm also worried that it will be hard to group users and route them to their Riff room.

**Comment by jaedoucette** [comment]
@adonahue Right, sorry, I'd seen that and forgotten about it. 

That makes sense to me. I _think_ Mattermost supports OAuth, and I think Amazon provides an Oauth2.0 login? In that case, maybe the signup & login process could be made pretty seemless: they'd have to be signed in to MTurk initially, so we can have them 'create' an account with 1 click (link Amazon to Oauth) and then 'login' next time would be automatic (provided that they are signed into MTurk at login time). Do you think that might work?

**Comment by jaedoucette** [comment]
Checked additional options:

Rocket.io 
  -  Supports anonymous users, some kinds of queuing, but poor notification support and detection of user being online?

Zulip:
  - No true support for anonymous users, and so doesn't appear much better than MatterMost.

Riot: 
  - Supports anonymous reading, but doesn't display anonymous users as present, and requires them to create an account in order to do so.

IRC:
  - Might be workable with a lot of bots / plugins, but doesn't look like there's an out-of-the-box solution

It still looks like our best bet might be Mattermost with an Amazon OAuth2 plugin.

Mattermost seems to make adding an OAuth2 service easy:
https://docs.mattermost.com/developer/oauth-2-0-applications.html

And Amazon offers an OAuth2 service:
https://developer.amazon.com/login-with-amazon

**Comment by jaedoucette** [comment]
Spike complete, and the decision is to go with a RiffEDU instance, and give up on the anonymous authentication feature. Followup work in Zenhub #116, #117, and #118.
